---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data: 
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc

---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  labels:
    name: bggapp-secret
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=