---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data: 
  WORDPRESS_DB_HOST: wordpress-mysql
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: wpsql-secret
  labels:
    name: wpsql-secret
data:
  WORDPRESS_DB_PASSWORD: Y2hhbmdlaXQ=
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

  