# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: db-deploy
#   labels:
#     name: db-deploy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       name: db-po
#   template:
#     metadata:
#       name: db-po
#       labels: 
#         name: db-po
#     spec:
#       volumes:
#       - name: my-vol
#         persistentVolumeClaim:
#           claimName: my-vol
#       containers:
#       - name: db-container
#         volumeMounts:
#         - mountPath: /var/lib/mysql
#           name: my-vol
#         image: stackupiss/bgg-database:v1
#         imagePullPolicy: IfNotPresent
#         ports:
#         - name: db-port
#           containerPort: 3306

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bggdb-svc
#   labels: 
#     name: bggdb-svc
# spec:
#   type: ClusterIP
#   selector:
#     name: db-po
#   ports:
#   - port: 3306
#     targetPort: 3306

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: my-vol
#   labels: 
#     name: my-vol
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: do-block-storage
#   accessModes:
#     - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom: 
         - secretRef:
            name: wpsql-secret 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
